version: "3"

networks:
  backend:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./conf/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3020:3020"
    volumes:
      - /home/ubuntu/volume/grafana-data:/var/lib/grafana
      - ./conf/grafana/provisioning/:/etc/grafana/provisioning/
    user: root
    restart: always
    privileged: true
    env_file: ".env"
    depends_on:
      - prometheus
    networks:
      - backend

#  node_exporter:
#    image: prom/node-exporter
#    volumes:
#      - /proc:/host/proc:ro
#      - /sys:/host/sys:ro
#      - /:/rootfs:ro
#    command:
#      - '--path.procfs=/host/proc'
#      - '--path.rootfs=/rootfs'
#      - '--path.sysfs=/host/sys'
#      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
#    ports:
#      - "9100:9100"
#    networks:
#      - backend

volumes:
  grafana-data:
  prometheus-data:
